FROM debian:trixie-slim AS base
LABEL maintainer="https://github.com/arbal"

EXPOSE 3493

ENV NUT_UPS_NAME=cyberpowerups
ENV NUT_UPS_DRIVER=usbhid-ups
ENV NUT_UPS_PORT=auto
ENV NUT_ADMIN_USER=admin
ENV NUT_ADMIN_PASSWORD=
ENV NUT_MONITOR_USER=monuser
ENV NUT_MONITOR_PASSWORD=

ARG PERM_INSTALL="tini nut-client nut-server usbutils"

RUN printf '%s\n' \
		'path-exclude /usr/share/doc/*' \
		'path-exclude /usr/share/man/*' \
		'path-exclude /usr/share/groff/*' \
		'path-exclude /usr/share/info/*' \
		'path-exclude /usr/share/lintian/*' \
		'path-exclude /usr/share/linda/*' \
		'path-exclude /usr/share/locale/*' \
		'path-include /usr/share/locale/en*' \
		> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
	apt-get update && \
	apt-get install -y --no-install-recommends $PERM_INSTALL && \
	apt-get clean && apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists/*

COPY start.sh /
RUN chmod +x /start.sh

ENTRYPOINT ["/usr/bin/tini", "--", "/start.sh"]
